// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoFabAPI.Models.Data.Contexto;

#nullable disable

namespace ProjetoFabAPI.Migrations
{
    [DbContext(typeof(DataContexto))]
    [Migration("20230309224716_CriacaoDeTabelas")]
    partial class CriacaoDeTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeEquipe")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipe", (string)null);
                });

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("IdFunc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFunc"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdFunc");

                    b.HasIndex("IdEquipe");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("ProjetoFabAPI.Models.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
