// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoFabAPI.Models.Data.Contexto;

#nullable disable

namespace ProjetoFabAPI.Migrations
{
    [DbContext(typeof(DataContexto))]
    partial class DataContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("IdEquipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipe"));

                    b.Property<string>("NomeEquipe")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEquipe");

                    b.ToTable("Equipe", (string)null);
                });

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Funcionario", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EquipeIdEquipe")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("integer");

                    b.HasKey("Nome");

                    b.HasIndex("EquipeIdEquipe");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("ProjetoFabAPI.Models.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("ProjetoFabAPI.Models.Domain.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeIdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });
#pragma warning restore 612, 618
        }
    }
}
